spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
        
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/  
    
    
  # freemarker  
  freemarker: 
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings: 
      number_format: '0.##########' 
    

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /sso-server



